# Generated by Django 3.0.6 on 2020-07-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0002_auto_20200509_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('document', models.CharField(max_length=80)),
                ('register', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('university_bond', models.CharField(choices=[('UNDER', 'Aluna(o) de graduação'), ('GRADUATION', 'Aluna(o) de pós-graduação'), ('CONTRACT', 'Terceirizada(o)'), ('PROFESSOR', 'Docente'), ('OTHER', 'Outro'), ('NOT_LINKED', 'Não tenho vínculo com a universidade')], max_length=50)),
                ('zip_code', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EnvolvedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('university_other', models.CharField(max_length=254)),
                ('university_bond', models.CharField(choices=[('UNDER', 'Aluna(o) de graduação'), ('GRADUATION', 'Aluna(o) de pós-graduação'), ('CONTRACT', 'Terceirizada(o)'), ('PROFESSOR', 'Docente'), ('OTHER', 'Outro'), ('NOT_LINKED', 'Não tenho vínculo com a universidade')], max_length=50)),
                ('university_bond_other', models.CharField(max_length=80)),
                ('person_bond', models.CharField(choices=[('NOT_KNOW', 'Não possui nenhum vínculo'), ('BOSS', 'Chefia'), ('COLLEAGUE', 'Colega de trabalho'), ('ADVISOR', 'Orientador(a)'), ('CLASS_COLLEAGUE', 'Colega de turma'), ('PERSONAL_FRIEND', 'Amigo(a) pessoal'), ('EX_', 'Ex-namorado(a), cônjuge(a), companheiro(a)'), ('OTHER', 'Outro')], max_length=50)),
                ('witness', models.CharField(choices=[('YES', 'Testemunha'), ('NO', 'Acusado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WhereHappened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='anonymous',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='exact_date_time',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='gender',
            field=models.CharField(choices=[('WOMAN', 'Mulher (trans ou cis)'), ('MAN', 'Homem (trans ou cis)'), ('NOT_BINARY', 'Gênero Não-binário'), ('OTHER', 'Outro'), ('NOT_ANSWER', 'Prefiro não responder')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='gender_other',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='complaint',
            name='person_position',
            field=models.CharField(choices=[('IAM', 'Eu sou a pessoa que vivenciou esse episódio'), ('VIEWER', 'Eu testemunhei esse episódio'), ('LISTEN', 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), ('ACCUSED', 'Eu fui acusado(a) de ser autor(a) de um episódio'), ('OTHER', 'Outro')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='person_position_other',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='complaint',
            name='person_position_support',
            field=models.CharField(choices=[('YES', 'Sim. Qual?'), ('NO', 'Não'), ('NOT', 'Não sei dizer')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='person_position_support_answer',
            field=models.CharField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='complaint',
            name='what_happened',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='why_anonymous',
            field=models.CharField(choices=[('0', 'Porque a pessoa que vivenciou o episódio não quer fazer uma queixa'), ('1', 'Porque tenho medo de retaliações que possam prejudicar a minha carreira e/ou a minha vida acadêmica'), ('2', 'Porque não quero receber apoio e orientações do SAVS'), ('3', 'Porque meu objetivo é que a universidade apenas tenha conhecimento deste episódio'), ('4', 'Outro')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='why_anonymous_other',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='witness',
            field=models.CharField(choices=[('YES', 'Sim. Qual?'), ('NO', 'Não'), ('NOT', 'Não sei dizer')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type_complaint',
            field=models.CharField(choices=[('DISCRI', 'Discriminação baseada em Gênero e/ou Sexualidade'), ('ASSALT', 'Assalto Sexual'), ('HARASS', 'Assédio Sexual'), ('ONLINE', 'Assédio Sexual Cibernético')], default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='university_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savs_app.UniversityPlace'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='savs_app.ComplaintPerson'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='where_happened',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='savs_app.WhereHappened'),
        ),
    ]
