# Generated by Django 3.0.6 on 2020-07-16 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0003_auto_20200715_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_position', models.TextField(default=None)),
                ('complaint_position_complement', models.TextField(null=True)),
                ('complaint_gender', models.TextField(default=None)),
                ('complaint_gender_complement', models.TextField(null=True)),
                ('complaint_connection_unicamp', models.TextField(default=None)),
                ('complaint_connection_unicamp_complement', models.TextField(null=True)),
                ('complaint_support_requested', models.TextField(default=None)),
                ('complaint_support_requested_complement', models.TextField(null=True)),
                ('episode_date', models.TextField(default=None)),
                ('episode_date_period', models.TextField(default=None)),
                ('episode_location', models.TextField(default=None)),
                ('episode_report', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifiedComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_position', models.TextField(default=None)),
                ('complaint_position_complement', models.TextField(null=True)),
                ('complaint_gender', models.TextField(default=None)),
                ('complaint_gender_complement', models.TextField(null=True)),
                ('complaint_name', models.TextField(default=None)),
                ('complaint_cpf', models.TextField(default=None)),
                ('complaint_is_social_name', models.BooleanField(default=None)),
                ('complaint_zipcode', models.TextField(default=None)),
                ('complaint_neighborhood', models.TextField(default=None)),
                ('complaint_city', models.TextField(default=None)),
                ('complaint_state', models.TextField(default=None)),
                ('complaint_address', models.TextField(default=None)),
                ('complaint_email', models.TextField(default=None)),
                ('complaint_telephone', models.TextField(default=None)),
                ('complaint_connection_unicamp', models.TextField(default=None)),
                ('complaint_connection_unicamp_complement', models.TextField(null=True)),
                ('complaint_institute', models.TextField(null=True)),
                ('complaint_ra', models.TextField(null=True)),
                ('complaint_course', models.TextField(null=True)),
                ('episode_date', models.TextField(default=None)),
                ('episode_date_period', models.TextField(default=None)),
                ('episode_location', models.TextField(default=None)),
                ('episode_report', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='person_bond',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='university_bond',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='university_bond_other',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='university_other',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='university_place',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='witness',
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='connecton_with_unicamp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='institute',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='is_author',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='relationship_with_unicamp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='anonymous',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savs_app.ComplaintPerson'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='exact_date_time',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='gender',
            field=models.CharField(choices=[('WOMAN', 'Mulher (trans ou cis)'), ('MAN', 'Homem (trans ou cis)'), ('NOT_BINARY', 'Gênero Não-binário'), ('OTHER', 'Outro'), ('NOT_ANSWER', 'Prefiro não responder')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='gender_other',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person_position',
            field=models.CharField(choices=[('IAM', 'Eu sou a pessoa que vivenciou esse episódio'), ('VIEWER', 'Eu testemunhei esse episódio'), ('LISTEN', 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), ('ACCUSED', 'Eu fui acusado(a) de ser autor(a) de um episódio'), ('OTHER', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person_position_other',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person_position_support',
            field=models.CharField(choices=[('YES', 'Sim. Qual?'), ('NO', 'Não'), ('NOT', 'Não sei dizer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person_position_support_answer',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type_complaint',
            field=models.CharField(choices=[('DISCRI', 'Discriminação baseada em Gênero e/ou Sexualidade'), ('ASSALT', 'Assalto Sexual'), ('HARASS', 'Assédio Sexual'), ('ONLINE', 'Assédio Sexual Cibernético')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='what_happened',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='where_happened',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savs_app.WhereHappened'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='why_anonymous',
            field=models.CharField(choices=[('0', 'Porque a pessoa que vivenciou o episódio não quer fazer uma queixa'), ('1', 'Porque tenho medo de retaliações que possam prejudicar a minha carreira e/ou a minha vida acadêmica'), ('2', 'Porque não quero receber apoio e orientações do SAVS'), ('3', 'Porque meu objetivo é que a universidade apenas tenha conhecimento deste episódio'), ('4', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='why_anonymous_other',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='witness',
            field=models.CharField(choices=[('YES', 'Sim. Qual?'), ('NO', 'Não'), ('NOT', 'Não sei dizer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='anonymous_complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savs_app.AnonymousComplaint'),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='identified_complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savs_app.IdentifiedComplaint'),
        ),
    ]
