# Generated by Django 3.0.6 on 2020-07-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0006_anonymouscomplaint_complaint_why_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envolvedperson',
            old_name='relationship_with_unicamp',
            new_name='relationship_with_victim',
        ),
    ]
