# Generated by Django 3.0.6 on 2020-07-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0008_auto_20200716_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_connection_unicamp',
            field=models.TextField(choices=[(1, 'Aluna(o) de graduação'), (2, 'Aluna(o) de pós-graduação'), (3, 'Terceirizada(o)'), (4, 'Docente'), (5, 'Outro'), (6, 'Não tenho vínculo com a universidade')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_gender',
            field=models.TextField(choices=[(1, 'Mulher (trans ou cis)'), (2, 'Homem (trans ou cis)'), (3, 'Gênero Não-binário'), (4, 'Outro'), (5, 'Prefiro não responder')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_position',
            field=models.TextField(choices=[(1, 'Eu sou a pessoa que vivenciou esse episódio'), (2, 'Eu testemunhei esse episódio'), (3, 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), (4, 'Eu fui acusado(a) de ser autor(a) de um episódio'), (5, 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_support_requested',
            field=models.TextField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sei dizer')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_why_anonymous',
            field=models.TextField(choices=[(1, 'Porque a pessoa que vivenciou o episódio não quer fazer uma queixa'), (2, 'Porque tenho medo de retaliações que possam prejudicar a minha carreira e/ou a minha vida acadêmica'), (3, 'Porque não quero receber apoio e orientações do SAVS'), (4, 'Porque meu objetivo é que a universidade apenas tenha conhecimento deste episódio'), (5, 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_date',
            field=models.TextField(choices=[(1, 'Na semana passada'), (2, 'No mês passado'), (3, 'No ano passado'), (4, 'Eu sei a data exata'), (5, 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_date_period',
            field=models.TextField(choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, 'Madrugada'), (5, 'Eu sei o horário exato'), (6, 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_connection_unicamp',
            field=models.TextField(choices=[(1, 'Aluna(o) de graduação'), (2, 'Aluna(o) de pós-graduação'), (3, 'Terceirizada(o)'), (4, 'Docente'), (5, 'Outro'), (6, 'Não tenho vínculo com a universidade')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_gender',
            field=models.TextField(choices=[(1, 'Mulher (trans ou cis)'), (2, 'Homem (trans ou cis)'), (3, 'Gênero Não-binário'), (4, 'Outro'), (5, 'Prefiro não responder')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_position',
            field=models.TextField(choices=[(1, 'Eu sou a pessoa que vivenciou esse episódio'), (2, 'Eu testemunhei esse episódio'), (3, 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), (4, 'Eu fui acusado(a) de ser autor(a) de um episódio'), (5, 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='episode_date',
            field=models.TextField(choices=[(1, 'Na semana passada'), (2, 'No mês passado'), (3, 'No ano passado'), (4, 'Eu sei a data exata'), (5, 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='episode_date_period',
            field=models.TextField(choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, 'Madrugada'), (5, 'Eu sei o horário exato'), (6, 'Não sei')], default=None),
        ),
    ]
