# Generated by Django 3.0.6 on 2020-07-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0009_auto_20200716_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_position',
            field=models.TextField(choices=[('experienced', 'Eu sou a pessoa que vivenciou esse episódio'), ('witnessed', 'Eu testemunhei esse episódio'), ('received', 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), ('accused', 'Eu fui acusado(a) de ser autor(a) de um episódio'), ('another', 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_position',
            field=models.TextField(choices=[('experienced', 'Eu sou a pessoa que vivenciou esse episódio'), ('witnessed', 'Eu testemunhei esse episódio'), ('received', 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), ('accused', 'Eu fui acusado(a) de ser autor(a) de um episódio'), ('another', 'Outro')], default=None),
        ),
    ]
