# Generated by Django 3.0.6 on 2020-07-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0011_auto_20200716_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_connection_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Não tenho vínculo com a universidade', 'Não tenho vínculo com a universidade')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_gender',
            field=models.TextField(choices=[('Mulher (trans ou cis)', 'Mulher (trans ou cis)'), ('Homem (trans ou cis)', 'Homem (trans ou cis)'), ('Gênero Não-binário', 'Gênero Não-binário'), ('Outro', 'Outro'), ('Prefiro não responder', 'Prefiro não responder')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_position',
            field=models.TextField(choices=[('Eu sou a pessoa que vivenciou esse episódio', 'Eu sou a pessoa que vivenciou esse episódio'), ('Eu testemunhei esse episódio', 'Eu testemunhei esse episódio'), ('Eu recebi um relato de uma pessoa que vivenciou esse episódio', 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), ('Eu fui acusado(a) de ser autor(a) de um episódio', 'Eu fui acusado(a) de ser autor(a) de um episódio'), ('Outro', 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_support_requested',
            field=models.TextField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei dizer', 'Não sei dizer')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_why_anonymous',
            field=models.TextField(choices=[('Porque a pessoa que vivenciou o episódio não quer fazer uma queixa', 'Porque a pessoa que vivenciou o episódio não quer fazer uma queixa'), ('Porque tenho medo de retaliações que possam prejudicar a minha carreira e/ou a minha vida acadêmica', 'Porque tenho medo de retaliações que possam prejudicar a minha carreira e/ou a minha vida acadêmica'), ('Porque não quero receber apoio e orientações do SAVS', 'Porque não quero receber apoio e orientações do SAVS'), ('Porque meu objetivo é que a universidade apenas tenha conhecimento deste episódio', 'Porque meu objetivo é que a universidade apenas tenha conhecimento deste episódio'), ('Outro', 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_date',
            field=models.TextField(choices=[('Na semana passada', 'Na semana passada'), ('No mês passado', 'No mês passado'), ('No ano passado', 'No ano passado'), ('Eu sei a data exata', 'Eu sei a data exata'), ('Não sei', 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_date_period',
            field=models.TextField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Madrugada', 'Madrugada'), ('Eu sei o horário exato', 'Eu sei o horário exato'), ('Não sei', 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_connection_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Não tenho vínculo com a universidade', 'Não tenho vínculo com a universidade')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_gender',
            field=models.TextField(choices=[('Mulher (trans ou cis)', 'Mulher (trans ou cis)'), ('Homem (trans ou cis)', 'Homem (trans ou cis)'), ('Gênero Não-binário', 'Gênero Não-binário'), ('Outro', 'Outro'), ('Prefiro não responder', 'Prefiro não responder')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_position',
            field=models.TextField(choices=[('Eu sou a pessoa que vivenciou esse episódio', 'Eu sou a pessoa que vivenciou esse episódio'), ('Eu testemunhei esse episódio', 'Eu testemunhei esse episódio'), ('Eu recebi um relato de uma pessoa que vivenciou esse episódio', 'Eu recebi um relato de uma pessoa que vivenciou esse episódio'), ('Eu fui acusado(a) de ser autor(a) de um episódio', 'Eu fui acusado(a) de ser autor(a) de um episódio'), ('Outro', 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='episode_date',
            field=models.TextField(choices=[('Na semana passada', 'Na semana passada'), ('No mês passado', 'No mês passado'), ('No ano passado', 'No ano passado'), ('Eu sei a data exata', 'Eu sei a data exata'), ('Não sei', 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='episode_date_period',
            field=models.TextField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Madrugada', 'Madrugada'), ('Eu sei o horário exato', 'Eu sei o horário exato'), ('Não sei', 'Não sei')], default=None),
        ),
    ]
