# Generated by Django 3.0.6 on 2020-07-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0012_auto_20200716_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='complainer_why_anonymous_complement',
            field=models.TextField(null=True),
        ),
    ]
