# Generated by Django 3.0.6 on 2020-07-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0013_anonymouscomplaint_complainer_why_anonymous_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='episode_date_complement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='episode_date_period_complement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='episode_location_complement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_location',
            field=models.TextField(choices=[('Na universidade', 'Na universidade'), ('Na minha casa', 'Na minha casa'), ('Em uma festa', 'Em uma festa'), ('Em um bar', 'Em um bar'), ('Foi online, por meio de:', 'Foi online, por meio de:'), ('Outro:', 'Outro:'), ('Não sei', 'Não sei')], default=None),
        ),
    ]
