# Generated by Django 3.0.6 on 2020-07-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0015_auto_20200716_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_connection_unicamp_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_gender_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_position_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_support_requested_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='complainer_why_anonymous_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_date_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_date_period_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='episode_location_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='anonymous_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savs_app.AnonymousComplaint'),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='identified_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savs_app.IdentifiedComplaint'),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='person_connecton_with_unicamp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='person_institute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='person_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='person_relationship_with_victim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_connection_unicamp_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_gender_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_institute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_position_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='complainer_ra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='episode_date_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='episode_date_period_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='episode_location_complement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
