# Generated by Django 3.0.6 on 2020-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0019_identifiedcomplaint_complainer_address_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifiedcomplaint',
            old_name='complainer_connection_unicamp',
            new_name='complainer_identified_connection_unicamp',
        ),
        migrations.RenameField(
            model_name='identifiedcomplaint',
            old_name='complainer_connection_unicamp_complement',
            new_name='complainer_identified_connection_unicamp_complement',
        ),
    ]
