# Generated by Django 3.0.6 on 2020-07-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0021_auto_20200718_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_episode_location',
            field=models.TextField(choices=[('Na universidade', 'Na universidade'), ('Na minha casa', 'Na minha casa'), ('Em uma festa', 'Em uma festa'), ('Em um bar', 'Em um bar'), ('Foi online, por meio de:', 'Foi online, por meio de:'), ('Outro:', 'Outro:'), ('Não sei', 'Não sei')], default=None),
        ),
    ]
