# Generated by Django 3.0.6 on 2020-07-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0022_auto_20200718_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_is_social_name',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
