# Generated by Django 3.0.6 on 2020-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0023_auto_20200719_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='person_connecton_with_unicamp',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='person_relationship_with_victim',
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous1',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous2',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous3',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous4',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous5',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='person_connecton_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Sem vínculo com a universidade', 'Sem vínculo com a universidade')], default=None),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='person_connecton_unicamp_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='person_course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='person_ra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='person_relationship_victim',
            field=models.TextField(choices=[('Não possui nenhum vínculo', 'Não possui nenhum vínculo'), ('Chefia', 'Chefia'), ('Colega de trabalho', 'Colega de trabalho'), ('Orientador(a)', 'Orientador(a)'), ('Colega de turma', 'Colega de turma'), ('Amigo(a) pessoal', 'Amigo(a) pessoal'), ('Ex-namorado(a), cônjuge(a), companheiro(a)', 'Ex-namorado(a), cônjuge(a), companheiro(a)'), ('Outro', 'Outro')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_connection_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Sem vínculo com a universidade', 'Sem vínculo com a universidade')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_episode_date_period',
            field=models.TextField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Madrugada', 'Madrugada'), ('Eu sei o horário exato', 'Eu sei o horário exato'), ('Não sei/Não se aplica', 'Não sei/Não se aplica')], default=None),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_episode_location',
            field=models.TextField(choices=[('Na universidade', 'Na universidade'), ('Na minha casa', 'Na minha casa'), ('Em uma festa', 'Em uma festa'), ('Em um bar', 'Em um bar'), ('Foi online', 'Foi online'), ('Outro', 'Outro'), ('Não sei', 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_connection_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Sem vínculo com a universidade', 'Sem vínculo com a universidade')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_episode_date_period',
            field=models.TextField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Madrugada', 'Madrugada'), ('Eu sei o horário exato', 'Eu sei o horário exato'), ('Não sei/Não se aplica', 'Não sei/Não se aplica')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_episode_location',
            field=models.TextField(choices=[('Na universidade', 'Na universidade'), ('Na minha casa', 'Na minha casa'), ('Em uma festa', 'Em uma festa'), ('Em um bar', 'Em um bar'), ('Foi online', 'Foi online'), ('Outro', 'Outro'), ('Não sei', 'Não sei')], default=None),
        ),
    ]
