# Generated by Django 3.0.6 on 2020-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0024_auto_20200722_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_why_anonymous5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_is_social_name',
            field=models.BooleanField(default=False),
        ),
    ]
