# Generated by Django 3.0.6 on 2020-07-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0025_auto_20200722_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envolvedperson',
            name='person_course',
        ),
        migrations.RemoveField(
            model_name='envolvedperson',
            name='person_ra',
        ),
        migrations.AddField(
            model_name='envolvedperson',
            name='person_relationship_victim_complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_connection_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Sem vínculo com a universidade', 'Sem vínculo com a universidade'), ('Não sei', 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='envolvedperson',
            name='person_connecton_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Sem vínculo com a universidade', 'Sem vínculo com a universidade'), ('Não sei', 'Não sei')], default=None),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_connection_unicamp',
            field=models.TextField(choices=[('Aluna(o) de graduação', 'Aluna(o) de graduação'), ('Aluna(o) de pós-graduação', 'Aluna(o) de pós-graduação'), ('Terceirizada(o)', 'Terceirizada(o)'), ('Docente', 'Docente'), ('Outro', 'Outro'), ('Sem vínculo com a universidade', 'Sem vínculo com a universidade'), ('Não sei', 'Não sei')], default=None),
        ),
    ]
