# Generated by Django 3.0.8 on 2020-07-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0030_auto_20200725_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonComplainSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Anonymous Complaint Summary',
                'verbose_name_plural': 'Anonymous Complaint Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('savs_app.anonymouscomplaint',),
        ),
    ]
