# Generated by Django 3.0.5 on 2020-07-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0031_anoncomplainsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentComplainSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Identified Complaint Summary',
                'verbose_name_plural': 'Identified Complaint Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('savs_app.identifiedcomplaint',),
        ),
    ]
