# Generated by Django 3.0.5 on 2020-08-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savs_app', '0032_identcomplainsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='anonymous_current_status',
            field=models.TextField(choices=[('Atendimento não iniciado', 'Atendimento não iniciado'), ('Em andamento', 'Em andamento'), ('Atendimento finalizado', 'Atendimento finalizado'), ('Aguardando retorno', 'Aguardando retorno'), ('Invalida', 'Invalida')], default='Atendimento não iniciado', null=True),
        ),
        migrations.AlterField(
            model_name='identifiedcomplaint',
            name='identified_current_status',
            field=models.TextField(choices=[('Atendimento não iniciado', 'Atendimento não iniciado'), ('Em andamento', 'Em andamento'), ('Atendimento finalizado', 'Atendimento finalizado'), ('Aguardando retorno', 'Aguardando retorno'), ('Invalida', 'Invalida')], default='Atendimento não iniciado', null=True),
        ),
    ]
